unblu:
  host: ${UNBLU_HOST}
  user: ${UNBLU_USER}
  password: ${UNBLU_PASSWORD}
  middleware:
    url: ${MIDDLEWARE_URL}
    name: Test middleware
  outbound-requests:
    secret: ${BOT_SECRET}
  bot:
    onboardingFilter: VISITORS
    person:
      firstName: Test
      lastName: Bot
      sourceId: Test middleware
    clean-previous: true
  webhook:
    secret: ${WEBHOOK_SECRET}
    clean-previous: true
